spring:
  data:
    mongodb:
      database: zicos
      host: localhost
      port: 27017
      
---
spring:
   profiles.active: prod
---
spring:
   profiles: prod
   datasource:
      continueOnError: true
      url: jdbc:mysql://10.6.184.183:3306/zicos_test?useSSL=false
      username: root
      password: root
      testWhileIdle: true
      validationQuery: SELECT 1

   jpa:
     show-sql: true
     hibernate:
       ddl-auto: update
       naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
     properties:  
       hibernate:
         id.new_generator_mappings: true 
         dialect: org.hibernate.dialect.MySQL5Dialect  
         
---
#Jenkin Server
jenkin.url: http://ec2-54-173-54-193.compute-1.amazonaws.com:25001
jenkin.host: 54.173.54.193
jenkin.port: 25001
jenkin.username: admin
jenkin.password: admin
#Proxy
proxy.enable: true
proxy.ip_address: 10.6.13.87
proxy.port: 8080
proxy.scheme: http
target.scheme: http
---
server:
  session:
    timeout: 1800
          
---
#Zicos forgot password
zicos.forgot.pwd: /auth/forgotPwdReset  
taas.mail.smtp.auth: mail.smtp.auth  
taas.mail.from: zicosadm@gmail.com
taas.mail.password: zicosadm@123

taas.mail.smtp.server.host.props: mail.smtp.host
taas.mail.host: 10.6.12.154
zicos.admin.user.id: Subbarao.Challagundla@itcinfotech.com
proxy.enable: true
taas.mail.smtp.starttls.enable: mail.smtp.starttls.enable
---
user:
  expiredate: 10            
---
proxy:
  ip_address: 10.6.13.87
  port: 8080
---
taas:
  mail:
    from: zicosadm@gmail.com
    password: zicosadm@123
---   
linux:
  hostname: 54.173.54.193
  username: singh19269
  password: new_password
  port: 25003
  shellScriptCmd: sudo ssh -i ZlabsCDH.pem ec2-user@172.31.38.185 "sh /home/ec2-user/quickstart.sh" 
  fetchTextDtlsCmd: sudo ssh -i ZlabsCDH.pem ec2-user@172.31.38.185 "cat /home/ec2-user/credential.txt" 
