
spring:
   session.store-type : none  

   datasource:
      continueOnError: true
      url: jdbc:mysql://localhost:3306/pbb
      username: root
      password: 
      testWhileIdle: true
      validationQuery: SELECT 1

   jpa:
     show-sql: true
     hibernate:
       ddl-auto: update
       naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
     properties:  
       hibernate:
         id.new_generator_mappings: true 
         dialect: org.hibernate.dialect.MySQL5Dialect  
         
---
spring:
  jackson:
    serialization.FAIL_ON_EMPTY_BEANS: false
      
server:
  session:
    timeout: 1800
    port: 8080    
---
server:
  context-path: /PBB
    
---
#pbb forgot password

mail.smtp.host: 10.6.12.154
mail.smtp.port : 25

mail.smtp.from : pavan.kuppam@itcinfotech.com

---
pbb.forgot.pwd: /auth/forgotPassword  


